### ISSUE TITLE
NoClassDefFoundException

### ISSUE THREAD

**Issue by mehmetminanc** [billdwhite/intellij-plugins-svgviewer2#6]
I am getting `org.ideaplugins.svgviewer.controller.project.SvgViewerProjectComponent@7c071dba: org/apache/batik/swing/JSVGCanvas` in IDEA 14 Community Edition build #141.2735 on my Ubuntu 14.04 machine. In a previous issue @VladRassokhin  specifically mentioned that `org.apache.batik` is prebundled with the Ultimate Edition and some other IntelliJ products.  Can I get it running on Community edition? Or how can I change IDEA's `classpath` for plugins?

```
org.ideaplugins.svgviewer.controller.project.SvgViewerProjectComponent@7c071dba: org/apache/batik/swing/JSVGCanvas
java.lang.NoClassDefFoundError: org/apache/batik/swing/JSVGCanvas
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
	at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:259)
	at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:255)
	at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:231)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:124)
	at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.java:77)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:66)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.ideaplugins.svgviewer.controller.project.SvgViewerProjectComponent.initToolWindow(SvgViewerProjectComponent.java:65)
	at org.ideaplugins.svgviewer.controller.project.SvgViewerProjectComponent.projectOpened(SvgViewerProjectComponent.java:47)
	at com.intellij.openapi.project.impl.ProjectImpl.projectOpened(ProjectImpl.java:393)
	at com.intellij.openapi.project.impl.ProjectImpl.access$200(ProjectImpl.java:73)
	at com.intellij.openapi.project.impl.ProjectImpl$MyProjectManagerListener.projectOpened(ProjectImpl.java:428)
	at com.intellij.openapi.project.impl.ProjectManagerImpl$3.projectOpened(ProjectManagerImpl.java:154)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.fireProjectOpened(ProjectManagerImpl.java:938)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.openProject(ProjectManagerImpl.java:461)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.loadAndOpenProject(ProjectManagerImpl.java:562)
	at com.intellij.ide.impl.ProjectUtil.openProject(ProjectUtil.java:182)
	at com.intellij.ide.RecentProjectsManagerImpl.doOpenProject(RecentProjectsManagerImpl.java:46)
	at com.intellij.ide.RecentProjectsManagerBase.doReopenLastProject(RecentProjectsManagerBase.java:357)
	at com.intellij.ide.RecentProjectsManagerBase$MyAppLifecycleListener.appStarting(RecentProjectsManagerBase.java:384)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:116)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:322)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:309)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:288)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:41)
	at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:177)
	at com.sun.proxy.$Proxy53.appStarting(Unknown Source)
	at com.intellij.idea.IdeaApplication$IdeStarter$2.run(IdeaApplication.java:328)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:332)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: org.apache.batik.swing.JSVGCanvas PluginClassLoader[SvgViewer 2, 2.0.1]
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:68)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 53 more
```

**Comment by billdwhite** [comment]
I'm not really sure if you'll be able to run this in the community edition.  Perhaps you can download the batik jar file and drop it into the ext folder of the JDK or maybe somewhere that the IDE can find it.  However I've never tried it.  You can try building an updated version using the Github repo that adds that jar as a dependency if all else fails.

**Comment by mehmetminanc** [comment]
I C/P'ed following all `.jar`s from the zip file downloaded off [the Apache Batik website](http://www.apache.org/dyn/closer.cgi/xmlgraphics/batik) into `idea/lib`. `ClassNotFound` errors were gone for good. And plugins works just fine. Thanks a lot!

I do not have any experience with IntelliJ plugins, sadly I am afraid I can't update dependencies for now.

BTW, that response speed was astonishing, thanks again.
